twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        uploaded_images_directory: '%images_directory_relative_path%'

when@test:
    twig:
        strict_variables: true
